package vistas;

import controladores.ControladorMonitoreo;
import controladores.iVistaMonitoreo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Fachada;
import modelo.Llamada;
import modelo.Puesto;
import modelo.Sector;

public class vistaMonitoreo extends javax.swing.JDialog implements iVistaMonitoreo {

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
    
    private ControladorMonitoreo controlador;

    public vistaMonitoreo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorMonitoreo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slcSector = new javax.swing.JComboBox();
        lblSectores = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaSectores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Monitoreo");
        setBackground(new java.awt.Color(204, 204, 255));

        slcSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slcSectorActionPerformed(evt);
            }
        });

        lblSectores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSectores.setText("Sectores ");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblListaSectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sector", "# Llamada", "Estado", "Inicio", "Fin", "# Puesto", "Trabajador", "Duracion", "Costo", "Cliente", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListaSectores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slcSector, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSectores, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblSectores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slcSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slcSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slcSectorActionPerformed

        mostrarTabla();
        
    }//GEN-LAST:event_slcSectorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        controlador.salir();
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    @Override
    public void cargarListaSectores(ArrayList<Sector> sectores) {
        slcSector.addItem("Todos");
        for (Sector s : sectores) {
            slcSector.addItem(s);
        }
    }

    public void mostrarTabla() {
        DefaultTableModel model = (DefaultTableModel) tblListaSectores.getModel();
        model.setNumRows(0);
        if (slcSector.getSelectedItem().toString().equals("Todos")) {

            ArrayList<Sector> sectores = Fachada.getInstancia().getListaSectores();
            for (Sector s : sectores) {
                for (Puesto p : s.getPuestos()) {
                    if (p.getLlamadaEnCurso() != null) {
                        model.addRow(new Object[]{s.getNombre(), p.getLlamadaEnCurso().getNumero(), "En curso", sdf.format(p.getLlamadaEnCurso().getFechaInicio()), "----",
                            p.getNumero(), p.getTrabajador().getNombre(), "----", "----", p.getLlamadaEnCurso().getCliente().getNombre(),
                            p.getLlamadaEnCurso().getCliente().getSaldo()});
                    }
                    for (Llamada ll : p.getLlamadasAtendidas()) {
                        model.addRow(new Object[]{s.getNombre(), ll.getNumero(), "Finalizada", sdf.format(ll.getFechaInicio()), sdf.format(ll.getFechaFin()), p.getNumero(),
                            p.getTrabajador().getNombre(), ll.getDuracion(), ll.getCosto(), ll.getCliente().getNombre(), ll.getCliente().getSaldo()});
                    }
                }
            }
        } else {
            Sector opcionSector = (Sector) slcSector.getSelectedItem();
            for (Puesto p : opcionSector.getPuestos()) {
                if (p.getLlamadaEnCurso() != null) {
                    model.addRow(new Object[]{"----", p.getLlamadaEnCurso().getNumero(), "En curso", sdf.format(p.getLlamadaEnCurso().getFechaInicio()), "----",
                        p.getNumero(), p.getTrabajador().getNombre(), "----", "----", p.getLlamadaEnCurso().getCliente().getNombre(),
                        p.getLlamadaEnCurso().getCliente().getSaldo()});
                }
                for (Llamada ll : p.getLlamadasAtendidas()) {
                    model.addRow(new Object[]{"----", ll.getNumero(), "Finalizada", sdf.format(ll.getFechaInicio()), sdf.format(ll.getFechaFin()), p.getNumero(),
                        p.getTrabajador().getNombre(), ll.getDuracion(), ll.getCosto(), ll.getCliente().getNombre(), ll.getCliente().getSaldo()});
                }
            }
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSectores;
    private javax.swing.JComboBox slcSector;
    private javax.swing.JTable tblListaSectores;
    // End of variables declaration//GEN-END:variables
}
