
package vistas;

import controladores.ControladorLlamadas;
import controladores.iVistaAtenderLlamadas;
import modelo.Trabajador;


public class vistaAtenderLlamadas extends javax.swing.JDialog implements iVistaAtenderLlamadas{

    private ControladorLlamadas controlador;
 
    public vistaAtenderLlamadas(java.awt.Frame parent, boolean modal, Trabajador trabajador) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorLlamadas(trabajador, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
